version: '2'

services:
  hangmanplus:
    build: ./hangmanplus
    depends_on:
      - phrase_service
    ports:
     - "8080:8080"
    environment:
      PHRASES_SERVICE_PORT_8081_TCP_ADDR: phrase_service
      PHRASES_SERVICE_PORT_8081_TCP_PORT: 8081
  phrase_service:
    build: ./hangman-phrase-service
    ports:
      - "8081:8081"

