version: '2'

services:
  hangmanplus:
    build: ./hangmanplus
    depends_on:
      - phrase_service
    ports:
     - "8080:8080"
    environment:
      PHRASES_SERVICE_PORT_8081_TCP_ADDR: phrase_service
      PHRASES_SERVICE_PORT_8081_TCP_PORT: 8081
  hangmanplus_panel:
    build: ./hangman-phrase-panel
    depends_on:
      - phrase_service
    ports:
     - "8082:8082"
    environment:
      PHRASES_SERVICE_PORT_8081_TCP_ADDR: phrase_service
      PHRASES_SERVICE_PORT_8081_TCP_PORT: 8081
  phrase_service:
    build: ./hangman-phrase-service
    depends_on:
      - phrases_db
    ports:
      - "8081:8081"
    environment:
      DB_HOST: phrases_db
  phrases_db:
    image: mongo
    volumes:
      - phrases_storage:/data/db

volumes:
  phrases_storage: {}
